version: '3.1'
  
services:
  yoti-drupal-7:
    build:
      context: ./docker/
      args:
        BRANCH: "SDK-104"
    ports:
     - "8007:80"
    volumes:
      - /var/www/html/sites/all/modules
      #- /var/www/html/profiles
      # this takes advantage of the feature in Docker that a new anonymous
      # volume (which is what we're creating here) will be initialized with the
      # existing content of the image at the same location
      - /var/www/html/sites/all/themes
    restart: always
  yoti-drupal-7-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_PORT: 3306
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    restart: always

